# Project: snake
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Snake.o Food.o
LINKOBJ  = main.o Snake.o Food.o
LIBS     = -L"E:/Software/Dev-Cpp/MinGW64/lib" -L"E:/Software/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/Software/Dev-Cpp/MinGW64/include" -I"E:/Software/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Software/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/Software/Dev-Cpp/MinGW64/include" -I"E:/Software/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Software/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/Software/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = snake.exe
CXXFLAGS = $(CXXINCS) -std=c++11
CFLAGS   = $(INCS) -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Snake.o: Snake.cpp
	$(CPP) -c Snake.cpp -o Snake.o $(CXXFLAGS)

Food.o: Food.cpp
	$(CPP) -c Food.cpp -o Food.o $(CXXFLAGS)
